#! /bin/bash

echo "Compilation :"

g++ main.cpp Cartes.cpp CartesEnergie.cpp Save.cpp Player.cpp CartesSpecial.cpp CartesCreature.cpp Utils.cpp Collection.cpp Menu.cpp -o executable


#g++ -Wall main.cpp Cartes.cpp CartesEnergie.cpp Save.cpp Player.cpp CartesSpecial.cpp CartesCreature.cpp Utils.cpp -o executable



./executable


